# Generated by Django 6.0.7 on 2026-07-19 18:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(db_index=True, help_text='Primeros caracteres, para identificarla sin revelarla.', max_length=8)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('strategies_evaluated', models.PositiveIntegerField(default=0)),
                ('alerts_created', models.PositiveIntegerField(default=0)),
                ('alerts_closed', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('rule_version', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('contracts', models.PositiveIntegerField(default=1, help_text='Tamano por senal, en contratos.')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('1.30'), help_text='Comision total del round-trip, por contrato.', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'strategies',
                'ordering': ['symbol', 'strategy_id'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_version', models.CharField(max_length=80)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('session_date', models.DateField(db_index=True)),
                ('direction', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('expired', 'Expired'), ('error', 'Error')], db_index=True, default='pending', max_length=10)),
                ('signal_ts', models.DateTimeField(help_text='Cierre de la vela que disparo.')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuando lo vio el scanner.')),
                ('underlying_at_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('occ_symbol', models.CharField(blank=True, max_length=32)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('strike', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contracts', models.PositiveIntegerField(default=1)),
                ('entry_ts', models.DateTimeField(blank=True, null=True)),
                ('entry_bid', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('entry_ask', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('entry_premium', models.DecimalField(blank=True, decimal_places=4, help_text='Prima pagada. Por convencion, el ASK.', max_digits=10, null=True)),
                ('exit_ts', models.DateTimeField(blank=True, null=True)),
                ('exit_premium', models.DecimalField(blank=True, decimal_places=4, help_text='Prima cobrada. Por convencion, el BID.', max_digits=10, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=40)),
                ('scheduled_exit_ts', models.DateTimeField(blank=True, help_text='Cuando le toca cerrar por tiempo. Lo usa el resolver.', null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('1.30'), max_digits=8)),
                ('net_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Contexto de la regla: rango, umbrales, features.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='powertradeai.strategy')),
            ],
            options={
                'ordering': ['-signal_ts'],
                'indexes': [models.Index(fields=['status', 'session_date'], name='powertradea_status_21a951_idx'), models.Index(fields=['strategy', 'session_date'], name='powertradea_strateg_13464f_idx')],
                'constraints': [models.UniqueConstraint(fields=('strategy', 'session_date', 'direction'), name='uniq_alert_per_strategy_session_direction')],
            },
        ),
    ]
