# Generated by Django 6.0.7 on 2026-07-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='uniq_alert_per_strategy_session_direction',
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('live', 'En vivo'), ('replay', 'Reconstruida')], db_index=True, default='live', max_length=8),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['source', 'session_date'], name='powertradea_source_c115c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('strategy', 'session_date', 'direction', 'source'), name='uniq_alert_per_strategy_session_direction_source'),
        ),
    ]
