# Generated by Django 6.0.7 on 2026-07-21 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0002_remove_alert_uniq_alert_per_strategy_session_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scan_loop', 'Scan loop'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('done', 'Terminada'), ('error', 'Error')], db_index=True, default='running', max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('symbols', models.JSONField(blank=True, default=list, help_text='Activos que miro esta corrida.')),
                ('goal', models.TextField(blank=True, help_text='La consigna que recibio.')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, help_text='Conclusion en breve.')),
                ('alerts_created', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('live', 'En vivo'), ('replay', 'Reconstruida'), ('agent', 'Agente')], db_index=True, default='live', max_length=8),
        ),
        migrations.AddField(
            model_name='alert',
            name='agent_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='powertradeai.agentrun'),
        ),
        migrations.CreateModel(
            name='AgentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('analysis', models.TextField(help_text='Lo que el agente concluye del activo.')),
                ('stance', models.CharField(blank=True, help_text='Sesgo: alcista / bajista / neutral / observando.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='powertradeai.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='powertradea_symbol_b5b387_idx')],
            },
        ),
    ]
