# Generated by Django 6.0.7 on 2026-07-21 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0003_agentrun_alter_alert_source_alert_agent_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=80)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='powertradeai.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', '-created_at'], name='powertradea_topic_8b67d1_idx')],
            },
        ),
    ]
