# Generated by Django 6.0.7 on 2026-07-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0004_agentnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(choices=[('above', 'Al subir a/por encima'), ('below', 'Al bajar a/por debajo')], max_length=8)),
                ('reason', models.TextField(blank=True, help_text='Que espera el agente en ese nivel / que hara.')),
                ('ref_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio cuando lo fijo, para saber de que lado venia.', max_digits=12, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='powertradeai.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'active'], name='powertradea_symbol_0563b6_idx')],
            },
        ),
    ]
