# Generated by Django 6.0.7 on 2026-07-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0005_agenttrigger'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alert',
            name='uniq_alert_per_strategy_session_direction_source',
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='trigger',
            field=models.CharField(choices=[('scan_loop', 'Scan loop'), ('manual', 'Manual'), ('training', 'Entrenamiento')], default='manual', max_length=16),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('live', 'En vivo'), ('replay', 'Reconstruida'), ('agent', 'Agente'), ('agent_train', 'Agente (entrenamiento)')], db_index=True, default='live', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('source__in', ['live', 'replay'])), fields=('strategy', 'session_date', 'direction', 'source'), name='uniq_alert_per_strategy_session_direction_source'),
        ),
    ]
