# Generated by Django 6.0.7 on 2026-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0006_remove_alert_uniq_alert_per_strategy_session_direction_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentanalysis',
            name='as_of',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentanalysis',
            name='mode',
            field=models.CharField(db_index=True, default='live', max_length=8),
        ),
        migrations.AddField(
            model_name='agentnote',
            name='as_of',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentnote',
            name='mode',
            field=models.CharField(db_index=True, default='live', max_length=8),
        ),
        migrations.AddField(
            model_name='agenttrigger',
            name='mode',
            field=models.CharField(db_index=True, default='live', max_length=8),
        ),
    ]
