# Generated by Django 6.0.7 on 2026-08-02 11:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def contain_legacy_state(apps, schema_editor):
    """Arranca el contrato v2 cerrado hasta ejecutar seed_strategies."""
    ApiKey = apps.get_model('powertradeai', 'ApiKey')
    Strategy = apps.get_model('powertradeai', 'Strategy')
    Alert = apps.get_model('powertradeai', 'Alert')

    ApiKey.objects.filter(scopes=[]).update(scopes=['read'])
    Strategy.objects.update(enabled=False)
    Alert.objects.filter(source='replay', status='pending').update(
        status='error', exit_reason='legacy_partial_replay')
    Alert.objects.filter(
        source__in=['agent', 'agent_train'], status='pending'
    ).update(status='error', exit_reason='legacy_pre_investep_v2')


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0007_agentanalysis_as_of_agentanalysis_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('done', 'Terminada'), ('error', 'Con errores')], db_index=True, default='running', max_length=8)),
                ('strategy_ids', models.JSONField(blank=True, default=list)),
                ('overwrite', models.BooleanField(default=False)),
                ('alerts_created', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='academy_strategy',
            field=models.CharField(blank=True, db_index=True, help_text='Codigo academico E01-E10; vacio para reglas no academicas.', max_length=3),
        ),
        migrations.AddField(
            model_name='alert',
            name='evaluation_version',
            field=models.CharField(db_index=True, default='legacy_v1', help_text='Linea base de evaluacion; evita mezclar resultados invalidados.', max_length=32),
        ),
        migrations.AddField(
            model_name='alert',
            name='strategy_branch',
            field=models.CharField(blank=True, help_text='Rama concreta, por ejemplo OPENING_GAP o INTRADAY_BREAK.', max_length=32),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='Permisos de la clave. Vacio conserva acceso legado de lectura.'),
        ),
        migrations.CreateModel(
            name='InvestepDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_code', models.CharField(db_index=True, max_length=3)),
                ('branch', models.CharField(max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=16)),
                ('direction', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('thesis', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('valid', 'Valida'), ('wait', 'Esperar confirmacion'), ('blocked', 'Bloqueada')], db_index=True, default='draft', max_length=8)),
                ('as_of', models.DateTimeField(db_index=True)),
                ('signal_ts', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('manual_hash', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=40)),
                ('rule_version', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(default='agent', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investep_decisions', to='powertradeai.agentrun')),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='investep_decision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert', to='powertradeai.investepdecision'),
        ),
        migrations.AddIndex(
            model_name='investepdecision',
            index=models.Index(fields=['symbol', 'strategy_code', '-as_of'], name='powertradea_symbol_0e79a5_idx'),
        ),
        migrations.AddIndex(
            model_name='investepdecision',
            index=models.Index(fields=['status', 'source', '-as_of'], name='powertradea_status_8ba4a7_idx'),
        ),
        migrations.RunPython(contain_legacy_state, migrations.RunPython.noop),
    ]
