# Generated by Django 6.0.7 on 2026-08-02 11:38

from django.db import migrations, models


def create_agent_lock(apps, schema_editor):
    RiskControl = apps.get_model('powertradeai', 'RiskControl')
    RiskControl.objects.get_or_create(key='agent')


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0008_replayrun_alert_academy_strategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('key', models.CharField(default='agent', max_length=32, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_agent_lock, migrations.RunPython.noop),
    ]
