# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("powertradeai", "0009_riskcontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("scan_loop", "Scan loop"),
                    ("agent_loop", "Agent loop"),
                    ("manual", "Manual"),
                    ("training", "Entrenamiento"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
    ]
