# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("powertradeai", "0010_alter_agentrun_trigger"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(source__in=["agent", "agent_train"])
                    & ~models.Q(academy_strategy="")
                ),
                fields=(
                    "source", "symbol", "academy_strategy",
                    "strategy_branch", "direction", "signal_ts",
                ),
                name="uniq_academic_agent_signal",
            ),
        ),
    ]
