# Generated by Django 6.0.7 on 2026-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powertradeai', '0011_alert_unique_academic_agent_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='investepdecision',
            name='validacion',
            field=models.CharField(choices=[('determinista', 'El servidor recalculo el setup'), ('juicio_agente', 'Solo el criterio del agente')], db_index=True, default='determinista', help_text='DETERMINISTA solo si existe validador mecanico (E01/E02).', max_length=16),
        ),
    ]
